/* eslint-disable */
// prettier-ignore
// GENERATED by scripts/gen_model_catalog.py — DO NOT EDIT.
// Edit src/backend/services/model_catalog.py and re-run the script.
//
// The `[1m]` extended-context suffix (e.g. 'claude-sonnet-4-6[1m]') and any
// other free-text model id are accepted by ModelSelector.vue via its onInput
// passthrough — a preset here is only a picker suggestion, never a hard gate.

export const MODEL_CATALOG = [
  {
    "id": "claude-opus-5",
    "label": "Claude Opus 5",
    "note": "Most capable Opus (latest)",
    "publicChannel": true,
    "adminDefaultSelectable": true,
    "recommended": false
  },
  {
    "id": "claude-fable-5",
    "label": "Claude Fable 5",
    "note": "Most capable — longest tasks (latest)",
    "publicChannel": true,
    "adminDefaultSelectable": true,
    "recommended": false
  },
  {
    "id": "claude-sonnet-5",
    "label": "Claude Sonnet 5",
    "note": "Fast + smart, 1M context (latest)",
    "publicChannel": true,
    "adminDefaultSelectable": true,
    "recommended": false
  },
  {
    "id": "claude-opus-4-8",
    "label": "Claude Opus 4.8",
    "note": "Legacy (prior Opus)",
    "publicChannel": true,
    "adminDefaultSelectable": true,
    "recommended": false
  },
  {
    "id": "claude-opus-4-7",
    "label": "Claude Opus 4.7",
    "note": "Legacy",
    "publicChannel": true,
    "adminDefaultSelectable": true,
    "recommended": false
  },
  {
    "id": "claude-opus-4-6",
    "label": "Claude Opus 4.6",
    "note": "Legacy",
    "publicChannel": true,
    "adminDefaultSelectable": true,
    "recommended": false
  },
  {
    "id": "claude-sonnet-4-6",
    "label": "Claude Sonnet 4.6",
    "note": "Fast + smart",
    "publicChannel": true,
    "adminDefaultSelectable": true,
    "recommended": true
  },
  {
    "id": "claude-haiku-4-5-20251001",
    "label": "Claude Haiku 4.5",
    "note": "Fastest, cheapest",
    "publicChannel": true,
    "adminDefaultSelectable": false,
    "recommended": false
  },
  {
    "id": "claude-opus-4-5-20251101",
    "label": "Claude Opus 4.5",
    "note": "Legacy",
    "publicChannel": false,
    "adminDefaultSelectable": false,
    "recommended": false
  },
  {
    "id": "claude-sonnet-4-5-20250929",
    "label": "Claude Sonnet 4.5",
    "note": "Legacy",
    "publicChannel": false,
    "adminDefaultSelectable": false,
    "recommended": false
  }
];
