#!/usr/bin/env python3
"""Generate JOURNEYS.md from the journey catalog (#2338, Rail R4).

Intent comes from `tests/journeys/catalog.yaml`, which is committed. STATUS
comes from CI artifacts at report time and is NOT — see the catalog header for
why a `last_green` in git either rots or spams history.

    # committed form: intent only, no status anywhere
    python scripts/ci/generate_journeys_md.py --out docs/testing/JOURNEYS.md

    # report form: same table plus a coverage line, for a CI summary
    python scripts/ci/generate_journeys_md.py --junit path/to/junit-dir

Stdlib + PyYAML only, so it runs in the same place the catalog test does.
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
CATALOG = REPO / "tests/journeys/catalog.yaml"
REGISTRY = REPO / "tests/registry.json"

GENERATED_HEADER = """<!-- GENERATED by scripts/ci/generate_journeys_md.py — do not edit by hand.
     Intent lives in tests/journeys/catalog.yaml. Run status deliberately does
     NOT live here or in the catalog: it is computed at report time from CI
     artifacts (#2338). Edit the catalog and regenerate. -->
"""


def load_catalog() -> dict:
    return yaml.safe_load(CATALOG.read_text())


def _norm_test_path(value: str | None) -> str:
    """One spelling for a test path, so three sources can be compared.

    They disagree by construction and every pair of them was mismatched:

      * the catalog stores REPO-relative   — `tests/journeys/test_x.py`
      * `tests/registry.json` stores TESTS-relative — `journeys/test_x.py`
      * JUnit `file` attributes are ROOTDIR-relative — `journeys/test_x.py`

    Normalising to the tests-relative form makes the joins in
    `harness_is_indexed` and `green_harnesses` actually match. Without it both
    silently answered "no" for every journey — invisible while every harness was
    still `null`, and permanently wrong the moment one was named.
    """
    if not value:
        return ""
    norm = str(value).strip().replace("\\", "/").lstrip("./")
    if norm.startswith("tests/"):
        norm = norm[len("tests/"):]
    return norm


def harness_is_indexed(harness: str | None) -> bool:
    """Does the registry know this harness file?

    The catalog LINKS to `tests/registry.json` rather than merging with it: the
    registry indexes tests, the catalog indexes promises. Joining them here — at
    report time — is what keeps both files single-purpose.

    The join reads `test_files[].file`. It previously did `str(f)` over the list,
    but `test_files` is a list of DICTS — so `str(f)` was a dict repr and
    `Path(str(f)).name` was nonsense. Combined with the tests/-vs-repo prefix
    mismatch above, the link AC #6 asks for was inert: the generated doc would
    have carried "Harnesses not present in tests/registry.json" for every journey,
    permanently and wrongly.
    """
    if not harness or not REGISTRY.exists():
        return False
    try:
        data = json.loads(REGISTRY.read_text())
    except Exception:
        return False
    want = _norm_test_path(harness)
    if not want:
        return False
    files = data.get("test_files")
    if isinstance(files, dict):
        return any(_norm_test_path(k) == want for k in files)
    if isinstance(files, list):
        for f in files:
            entry = f.get("file") if isinstance(f, dict) else f
            if _norm_test_path(entry) == want:
                return True
    return False


def green_harnesses(junit_dir: str) -> set[str]:
    """Harness files with at least one PASSING case and zero failures/errors.

    Absence of evidence is not green, and that has two shapes, not one. The
    docstring used to state the first and be silent about the second:

      1. A harness in no artifact at all is not counted — that is why coverage
         is reported with its denominator.
      2. A harness whose every case SKIPPED is also not green. `skipped` is
         neither `failure` nor `error`, so the old rule recorded it as green. It
         would have gone wrong on the very first journey to carry a path: J03's
         harness is the credential-bound one that skips on every PR-triggered
         run, so the first harness named would also have been the first
         misreported.

    Keys are normalised (`_norm_test_path`), because JUnit `file` attributes are
    rootdir-relative (`journeys/test_x.py`) while the catalog is repo-relative
    (`tests/journeys/test_x.py`) — compared raw, every journey read `no
    evidence` forever.
    """
    seen: dict[str, bool] = {}
    passed: set[str] = set()
    for path in glob.glob(os.path.join(junit_dir, "**", "*.xml"), recursive=True):
        try:
            root = ET.parse(path).getroot()
        except ET.ParseError:
            continue
        for case in root.iter("testcase"):
            f = _norm_test_path(case.get("file"))
            if not f:
                continue
            bad = any(case.find(t) is not None for t in ("failure", "error"))
            skipped = case.find("skipped") is not None
            seen[f] = seen.get(f, True) and not bad
            if not bad and not skipped:
                passed.add(f)
    return {f for f, ok in seen.items() if ok and f in passed}


def render(catalog: dict, junit_dir: str | None) -> str:
    rows = []
    built = green = 0
    greens = green_harnesses(junit_dir) if junit_dir else set()

    for j in catalog["journeys"]:
        if j["built"]:
            built += 1
        state = ""
        if junit_dir:
            if j["harness"] and _norm_test_path(j["harness"]) in greens:
                state = " · green"
                green += 1
            elif j["built"]:
                state = " · no evidence"
        inv = ", ".join(j["invariants"]) or "—"
        harness = f"`{j['harness']}`" if j["harness"] else "—"
        rows.append(
            f"| **{j['id']}** | {j['promise']} | {j['actor']} | "
            f"{', '.join(j['lanes'])} | {j['tier']} | "
            f"{'yes' if j['built'] else '**no**'}{state} | {harness} | {inv} | "
            f"#{j['issue']} |"
        )

    out = [GENERATED_HEADER, "# Journeys\n",
           "Every promise Trinity makes, in the words of whoever it is made to.",
           "`built: no` is a real answer and an honest one — the list exists so",
           "coverage debt is queryable rather than rediscovered.\n",
           "| id | promise | actor | lanes | tier | built | harness | invariants | issue |",
           "|---|---|---|---|---|---|---|---|---|"]
    out.extend(rows)

    total = len(catalog["journeys"])
    out.append("")
    if junit_dir:
        pct = (100.0 * green / total) if total else 0.0
        out.append(f"**Coverage at report time: {green}/{total} journeys built "
                   f"and green ({pct:.0f}%).** {built} declared built.")
        out.append("")
        out.append("_Computed from CI artifacts, not from this file. A harness "
                   "with no artifact counts as no evidence, never as green._")
    else:
        out.append(f"**{built} of {total} journeys built.** Green/red is NOT "
                   f"recorded here — regenerate with `--junit <dir>` against CI "
                   f"artifacts for a coverage figure.")

    unindexed = [j["id"] for j in catalog["journeys"]
                 if j["harness"] and not harness_is_indexed(j["harness"])]
    if unindexed:
        out.append("")
        out.append(f"_Harnesses not present in `tests/registry.json`: "
                   f"{', '.join(unindexed)}._")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", help="write here instead of stdout")
    ap.add_argument("--junit", help="directory of CI JUnit XML; adds coverage")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if --out is stale (for CI)")
    args = ap.parse_args()

    body = render(load_catalog(), args.junit)

    if args.check:
        if not args.out:
            print("--check needs --out", file=sys.stderr)
            return 2
        current = Path(args.out).read_text() if Path(args.out).exists() else ""
        if current != body:
            print(f"{args.out} is stale — regenerate it "
                  f"(python {Path(__file__).relative_to(REPO)} --out {args.out})",
                  file=sys.stderr)
            return 1
        return 0

    if args.out:
        Path(args.out).write_text(body)
    else:
        sys.stdout.write(body)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
