"""
A2A (Agent-to-Agent) protocol endpoints (#737 card; ent#157 inbound server;
#736 outbound calls).

Three surfaces live here:

1. `GET /api/agents/{name}/a2a/agent-card` (#737) — the authenticated
   per-agent Agent Card. External orchestrators (AWS Bedrock, Azure
   Copilot, Google ADK) consume it to discover what the agent can do
   without knowing Trinity's internal API.
2. The **inbound server** (ent#157) on the prefix-less
   `a2a_server_router`: a public `GET /a2a/{name}/.well-known/agent-card.json`
   plus the JSON-RPC task endpoint `POST /a2a/{name}`. Exposure is opt-in
   per agent (`agent_ownership.a2a_exposed`, default OFF) and everything
   non-exposed / inaccessible answers a uniform 404 (Invariant #8), so the
   public surface is not an enumeration oracle.
3. The **outbound client** (#736): `POST /api/agents/{name}/a2a/call` and
   `POST /api/agents/{name}/a2a/task`, which let a Trinity agent task an
   EXTERNAL A2A agent. The target is never supplied by the caller — it is a
   reference into an operator-registered endpoint list, resolved server-side —
   and the orchestration lives in `services/a2a_outbound_service.py`; the
   routes below are auth, the HTTP error map, and the audit row.

The card is generated by the backend from the agent's `template.yaml`
+ ownership metadata — no agent-server changes required. The agent
container doesn't need to be running for a stopped agent's card to
be served; we fall back to the metadata carried on the Docker
container's labels, which survive `docker stop`.
"""

from __future__ import annotations

import asyncio
import json
import logging
import uuid
from typing import Any, Dict, Optional

import httpx
from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import JSONResponse, StreamingResponse
from fastapi.routing import APIRoute

from database import db
from dependencies import AuthorizedAgentByName, get_current_user
from models import A2ACallRequest, A2ACallResponse, A2ATaskRequest, User
from routers.public import _get_client_ip
from services import (
    a2a_gate,
    a2a_outbound_service,
    a2a_protocol,
    idempotency_service,
    rate_limiter,
)
from services.a2a_card_service import generate_a2a_card
from services.aauth import config as aauth_config
from services.aauth import httpsig as aauth_httpsig
from services.aauth import inbound as aauth_inbound
from services.aauth import verifier as aauth_verifier
from services.a2a_client import A2ACallError
from services.a2a_outbound_service import (
    A2AAAuthRefused,
    A2AEndpointNotFound,
    A2AOutboundDisabled,
)
from services.idempotency_service import EffectInProgressError
from services.agent_auth import agent_httpx_client
from services.docker_service import get_agent_container
from services.platform_audit_service import AuditEventType, platform_audit_service
from services.task_execution_service import (
    dispatch_and_await_terminal,
    get_task_execution_service,
    terminate_execution_on_agent,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/agents", tags=["a2a"])

#: The JSON-RPC task route, the only route AAuth can authenticate (ent#623).
_A2A_RPC_PATH = "/a2a/{agent_name}"


class _A2AServerRoute(APIRoute):
    """Routes an AAuth-signed task request around the bearer dependency (ent#623).

    `POST /a2a/{name}` authenticates a bearer MCP key through
    `Depends(get_current_user)`, which 401s any request without one before the
    handler runs. An AAuth caller carries no bearer, so the dependency cannot
    simply be made conditional: FastAPI resolves every declared dependency.
    Instead, a request that carries `Signature-Key` while AAuth is live takes a
    separate entry point (`_a2a_aauth_jsonrpc`); every other request — including
    every request while the flag is off — goes through the untouched route
    handler, so the bearer path, its 401s and its dependency overrides are
    byte-identical to before. Detection keys on `Signature-Key` only: other
    RFC 9421 senders (e.g. Web Bot Auth) do not send it.

    While AAuth is live, a bearer-less 401 also advertises how to sign
    (`Accept-Signature`, `AAuth-Requirement`) — a caller discovers the scheme
    from the challenge rather than out of band.
    """

    def get_route_handler(self):
        handler = super().get_route_handler()
        if self.path != _A2A_RPC_PATH or "POST" not in (self.methods or ()):
            return handler

        async def route(request: Request):
            if "signature-key" in request.headers:
                issuer = aauth_config.active_issuer()
                if issuer:
                    return await _a2a_aauth_jsonrpc(request, issuer)
            try:
                return await handler(request)
            except HTTPException as exc:
                if (
                    exc.status_code == 401
                    and "authorization" not in request.headers
                    and aauth_config.active_issuer()
                ):
                    exc.headers = {**(exc.headers or {}), **_AAUTH_CHALLENGE_HEADERS}
                raise

        return route


# ent#157: the public A2A inbound server (well-known card + JSON-RPC task
# endpoint). Separate router (no /api prefix) so external orchestrators reach
# the spec-shaped `/a2a/{name}/.well-known/agent-card.json` + `POST /a2a/{name}`.
a2a_server_router = APIRouter(tags=["a2a-server"], route_class=_A2AServerRoute)


def _base_url_from_request(request: Request) -> str:
    """Compute the external base URL for card `url` construction.

    Order of preference:
      1. `PUBLIC_CHAT_URL` env if set — this is what external
         consumers reach Trinity through (Cloudflare tunnel, etc.).
      2. `FRONTEND_URL` env — second-best for self-hosted setups.
      3. The request's own scheme + host — works fine for clients
         that fetched the card from the same host they'll call.

    Returns "" if none of the above resolve, signalling the card
    generator to omit URL fields rather than emit a broken URL.
    """
    from config import FRONTEND_URL, PUBLIC_CHAT_URL  # local import: avoid circular at module load

    if PUBLIC_CHAT_URL:
        return PUBLIC_CHAT_URL.rstrip("/")
    if FRONTEND_URL:
        return FRONTEND_URL.rstrip("/")
    if request.url:
        return f"{request.url.scheme}://{request.url.netloc}"
    return ""


async def _fetch_template_data(agent_name: str, container) -> dict:
    """Fetch template.yaml data from the agent's container (when
    running) or fall back to docker labels (when stopped).

    Mirrors the existing `GET /api/agents/{name}/info` fallback logic
    so a stopped agent still produces a usable card. Network errors
    are logged and treated as "use the label fallback" — we never let
    a transient agent-server failure 5xx the card endpoint.
    """
    labels = container.labels or {}
    label_fallback = {
        "name": agent_name,
        "display_name": labels.get("trinity.template", agent_name),
        "description": "",
        "version": "1.0.0",
        "capabilities": [],
        "use_cases": [],
    }

    if container.status != "running":
        return label_fallback

    try:
        agent_url = f"http://agent-{agent_name}:8000/api/template/info"
        async with agent_httpx_client(agent_name, timeout=5.0) as client:
            response = await client.get(agent_url)
            if response.status_code == 200:
                data = response.json()
                # The agent-server returns `has_template=False` when
                # the agent was created without a template.yaml. Use
                # the label fallback in that case so the card still
                # advertises the agent's name + provider, just with
                # an empty skills list.
                if data.get("has_template") is False:
                    return label_fallback
                return data
            logger.info(
                f"A2A card: agent-server /api/template/info returned "
                f"{response.status_code} for {agent_name}; using label fallback"
            )
    except httpx.TimeoutException:
        logger.info(f"A2A card: agent-server timeout for {agent_name}; using label fallback")
    except Exception as e:  # noqa: BLE001 — defensive: never 5xx the card
        logger.warning(f"A2A card: agent-server unreachable for {agent_name}: {e}")

    return label_fallback


#: Hosts already warned about, so the check below costs one log line, not one
#: per card fetch.
_AAUTH_HOST_WARNED: set = set()


def _warn_issuer_card_mismatch(issuer: str, base_url: str) -> None:
    """A card served under a different host than the AAuth issuer is unusable.

    The caller signs `@authority` from the card's `url`; the callee verifies it
    against its configured issuer host. If `PUBLIC_CHAT_URL` / `FRONTEND_URL`
    and `aauth_issuer` name different hosts, every signed call fails
    `invalid_signature` and nothing says why (ent#623).
    """
    from urllib.parse import urlsplit

    card_host = (urlsplit(base_url).hostname or "").lower()
    issuer_host = aauth_config.issuer_host(issuer)
    if card_host and card_host != issuer_host and card_host not in _AAUTH_HOST_WARNED:
        _AAUTH_HOST_WARNED.add(card_host)
        logger.warning(
            "[aauth] served card host %s != aauth_issuer host %s — signed calls to "
            "this instance will fail invalid_signature until they agree "
            "(set PUBLIC_CHAT_URL to the issuer origin)", card_host, issuer_host,
        )


def _card_with_exposed_skills(
    agent_name: str,
    template_data: dict,
    base_url: str,
) -> dict:
    """Build the card, then narrow `skills[]` to what this agent may advertise.

    ent#180. THE single place a card is produced: both the authenticated
    per-agent card (#737) and the public well-known card (ent#157) go through
    here, so the two surfaces can never answer "what does this agent do?"
    differently (requirements §32.4 FR-3) and a future third surface gets the
    filter by default rather than by remembering.

    `generate_a2a_card` stays pure (no I/O) — the provider lookup lives here.
    OSS builds register no provider, so this is the identity function and the
    card is byte-identical to before ent#180.
    """
    issuer = aauth_config.active_issuer()
    if issuer and base_url:
        _warn_issuer_card_mismatch(issuer, base_url)
    card = generate_a2a_card(
        agent_name=agent_name,
        template_data=template_data,
        base_url=base_url,
        aauth_resource_metadata_url=(
            f"{issuer}/.well-known/aauth-resource.json" if issuer else None
        ),
    )
    card["skills"] = a2a_gate.filter_exposed_skills(agent_name, card.get("skills") or [])
    return card


@router.get("/{agent_name}/a2a/agent-card")
async def get_agent_card(
    agent_name: AuthorizedAgentByName,
    request: Request,
):
    """Return the A2A Agent Card (protocol `0.3.0`) for `agent_name`.

    Auth: requires `AuthorizedAgentByName` (same gate as the rest of
    the per-agent endpoints — owner, admin, or shared user). The
    issue's "public card" framing refers to the *content* of the
    card (no sensitive fields), not unauthenticated access.

    This route stays authenticated and serves ANY accessible agent. The
    unauthenticated public card is the separate, opt-in `a2a_exposed`
    surface below (`a2a_well_known_card`) — that access-policy decision
    is the exposure flag, per agent, default OFF.

    404 if the agent doesn't exist or the caller doesn't have access.
    Card generation never 5xx's — agent-server failures fall back to
    Docker labels.
    """
    container = get_agent_container(agent_name)
    if not container:
        raise HTTPException(status_code=404, detail="Agent not found")

    template_data = await _fetch_template_data(agent_name, container)
    base_url = _base_url_from_request(request)
    card = _card_with_exposed_skills(
        agent_name=agent_name,
        template_data=template_data,
        base_url=base_url,
    )
    return card


# ===========================================================================
# ent#157 — A2A inbound server (public well-known card + JSON-RPC task endpoint)
# ===========================================================================

# JSON-RPC 2.0 + A2A error codes. Sourced from `services/a2a_protocol.py`
# (#736 F19) rather than re-declared: the outbound client speaks the same
# dialect — most immediately against a remote Trinity, since #738 federation is
# downstream of #736 — and two copies of a protocol vocabulary is how a dialect
# table rots. The module-private aliases are kept so the existing call sites
# below read unchanged.
_RPC_PARSE_ERROR = a2a_protocol.RPC_PARSE_ERROR
_RPC_INVALID_REQUEST = a2a_protocol.RPC_INVALID_REQUEST
_RPC_METHOD_NOT_FOUND = a2a_protocol.RPC_METHOD_NOT_FOUND
_RPC_INVALID_PARAMS = a2a_protocol.RPC_INVALID_PARAMS
_RPC_INTERNAL_ERROR = a2a_protocol.RPC_INTERNAL_ERROR
_A2A_TASK_NOT_FOUND = a2a_protocol.A2A_TASK_NOT_FOUND
_A2A_TASK_NOT_CANCELABLE = a2a_protocol.A2A_TASK_NOT_CANCELABLE
_A2A_UNSUPPORTED = a2a_protocol.A2A_UNSUPPORTED

# The well-known card route is unauthenticated and published by design, so the
# agent name is public. Each hit costs a DB read + a live Docker API call + an
# HTTP call into the agent container, so an unthrottled flood stalls the event
# loop and hammers the fleet from one URL. Per-IP limit mirrors the other
# unauthenticated routes: public.py (PUBLIC_LINK_LOOKUP_RATE_LIMIT),
# files.py (_DOWNLOAD_RATE_LIMIT), webhooks.py (#1424).
A2A_CARD_RATE_LIMIT = 60      # max card fetches per IP
A2A_CARD_RATE_WINDOW = 60     # per minute

# Cap the JSON-RPC body before parsing it (the #1424 / #1083 shape). nginx caps
# at 25m, but :8000 may be reachable directly.
_MAX_RPC_BODY_BYTES = a2a_protocol.MAX_RPC_BODY_BYTES


def _rpc_error(rpc_id: Any, code: int, message: str, data: Any = None) -> JSONResponse:
    """A JSON-RPC 2.0 error envelope. Transport stays HTTP 200 — the error is
    carried in the body (auth failures are the exception: those are HTTP 401 via
    the dependency, before we ever parse an envelope)."""
    err: Dict[str, Any] = {"code": code, "message": message}
    if data is not None:
        err["data"] = data
    return JSONResponse({"jsonrpc": "2.0", "id": rpc_id, "error": err})


def _rpc_result(rpc_id: Any, result: Any) -> JSONResponse:
    return JSONResponse({"jsonrpc": "2.0", "id": rpc_id, "result": result})


def _exec_field(row: Any, name: str) -> Any:
    """Read a field from an execution row that may be a ScheduleExecution model
    (attribute) OR a dict (mapping) — `db.get_execution` returns the former."""
    if isinstance(row, dict):
        return row.get(name)
    return getattr(row, name, None)


def _text_from_message(message: Dict[str, Any]) -> str:
    """Concatenate the text parts of an A2A message (v0.3 part kind='text')."""
    parts = message.get("parts") if isinstance(message, dict) else None
    if not isinstance(parts, list):
        return ""
    out = []
    for p in parts:
        if isinstance(p, dict) and p.get("kind") == "text" and isinstance(p.get("text"), str):
            out.append(p["text"])
    return "\n".join(out).strip()


def _task_object(execution_id: str, state: str, *, text: Optional[str] = None,
                 context_id: Optional[str] = None, error: Optional[str] = None) -> Dict[str, Any]:
    """Build an A2A Task object. `state`: submitted|working|completed|failed|canceled."""
    task: Dict[str, Any] = {
        "id": execution_id,
        "contextId": context_id or execution_id,
        "kind": "task",
        "status": {"state": state},
    }
    if text is not None:
        task["artifacts"] = [{
            "artifactId": uuid.uuid4().hex,
            "parts": [{"kind": "text", "text": text}],
        }]
    if error is not None:
        task["status"]["message"] = {
            "role": "agent",
            "parts": [{"kind": "text", "text": error}],
            "messageId": uuid.uuid4().hex,
        }
    return task


def _a2a_state_for(status: str) -> str:
    """Map a Trinity TaskExecutionStatus to an A2A task state.

    A cancelled execution is `canceled`, not `failed` — the A2A spec treats them
    as distinct terminal states and a caller that cancelled its own task should
    not be told the task errored.
    """
    return {"success": "completed", "cancelled": "canceled"}.get(status, "failed")


def _a2a_idem_scope(agent_name: str, current_user: Optional[User],
                    aauth: Optional["aauth_verifier.VerifiedAgent"] = None) -> str:
    """Dedup scope for an inbound A2A `messageId`: per (agent, caller principal).

    `messageId` is a **peer-controlled** protocol field that A2A SDKs generate
    automatically, and the spec only requires uniqueness *per client* — two
    callers legitimately collide on `"req-1"`. Scoping on the agent alone would
    make one caller's `messageId` resolve to another caller's stored snapshot,
    which carries the agent's full response text: caller B would receive caller
    A's output and B's own task would silently never run.

    Keying the scope on the caller principal gives every caller a private
    `messageId` namespace, so a collision can only ever replay the caller's own
    prior result. `mcp_key_id` is preferred over `username` because agent-scoped
    keys all resolve to the same owner user — the key id is what distinguishes
    two agents calling on the same owner's behalf.
    """
    if aauth is not None:
        # ent#623: an AAuth caller's namespace is its verified agent identity.
        return f"a2a:{agent_name}:aauth|{aauth.identity}"
    principal = (
        getattr(current_user, "mcp_key_id", None)
        or getattr(current_user, "username", None)
        or "anonymous"
    )
    return f"a2a:{agent_name}:{principal}"


async def _serve_card(agent_name: str, request: Request) -> Optional[Dict[str, Any]]:
    """Build the honest A2A card for an EXPOSED agent, or None (→ uniform 404).

    Uniform 404 for non-exposed / non-existent so the public surface is not an
    enumeration oracle. Exposure can only be set by the entitled enterprise
    setter, so in an OSS-only / unentitled build every agent is non-exposed and
    this always returns None (routes 404) — safe by default.
    """
    if not db.get_a2a_exposed(agent_name):
        return None
    container = get_agent_container(agent_name)
    if not container:
        return None
    template_data = await _fetch_template_data(agent_name, container)
    return _card_with_exposed_skills(
        agent_name=agent_name,
        template_data=template_data,
        base_url=_base_url_from_request(request),
    )


@a2a_server_router.get("/a2a/{agent_name}/.well-known/agent-card.json")
async def a2a_well_known_card(agent_name: str, request: Request):
    """Public (unauthenticated) A2A discovery card for an exposed agent.

    404 (uniform) when the agent is non-existent or not A2A-exposed. The card's
    `url` points at `POST /a2a/{name}` (the JSON-RPC task endpoint).

    Per-IP rate limited BEFORE any DB/Docker/agent work — the expensive part of
    serving a card is exactly what an unauthenticated flood would amplify.
    Trusted-proxy aware (so X-Forwarded-For can't be spoofed past it) and
    fail-open, per the shared limiter's contract.
    """
    rate_limiter.enforce(
        f"a2a_card_ip:{_get_client_ip(request)}",
        A2A_CARD_RATE_LIMIT,
        A2A_CARD_RATE_WINDOW,
        detail="Too many A2A card requests from this address.",
    )
    card = await _serve_card(agent_name, request)
    if card is None:
        raise HTTPException(status_code=404, detail="Not found")
    return card


def _authorize_inbound(current_user: User, agent_name: str) -> None:
    """Exposure + access + allow-list gate for an inbound A2A task. Raises
    HTTPException(404) for non-exposed/inaccessible (uniform — no enumeration),
    HTTPException(403) when the caller is off the per-agent allow-list."""
    if not db.get_a2a_exposed(agent_name):
        raise HTTPException(status_code=404, detail="Not found")
    if not db.can_user_access_agent(current_user.username, agent_name):
        raise HTTPException(status_code=404, detail="Not found")
    caller_identity = getattr(current_user, "email", None) or current_user.username
    if not a2a_gate.check_inbound_allowed(agent_name, caller_identity):
        raise HTTPException(status_code=403, detail="Caller not on the agent's A2A inbound allow-list")


async def _run_a2a_task(agent_name: str, text: str, current_user: User):
    """Bridge one inbound A2A message into the Trinity execution stack.

    #2524: goes through `dispatch_and_await_terminal`, not `execute_task`
    directly. Both callers below consume `result.status` / `result.response` to
    build the JSON-RPC artifact they hand a remote caller, and under
    `PULL_MODE_PILOT_AGENTS` a dispatch returns `QUEUED` as soon as the row is on
    the durable queue — the turn runs later, in the agent's worker. The adapter
    waits out that queue and rebuilds the result from the row, so the artifact is
    the same whether the turn ran inside this await or somewhere else. That is
    what lets `a2a` join `pull_pilot.PULL_REACHABLE_TRIGGERS` without touching the
    JSON-RPC contract, which is one request / one artifact and has no receipt to
    hand back.
    """
    return await dispatch_and_await_terminal(
        agent_name=agent_name,
        message=text,
        triggered_by="a2a",
        source_user_id=getattr(current_user, "id", None),
        source_user_email=getattr(current_user, "email", None),
        source_mcp_key_id=getattr(current_user, "mcp_key_id", None),
    )


@a2a_server_router.post(_A2A_RPC_PATH)
async def a2a_jsonrpc(
    agent_name: str,
    request: Request,
    current_user: User = Depends(get_current_user),
):
    """A2A JSON-RPC 2.0 task endpoint. Bearer = a Trinity MCP API key (validated
    by `get_current_user` — fail-closed 401). Methods: message/send,
    message/stream (SSE), tasks/get, tasks/cancel.

    An AAuth-signed request (ent#623) never reaches this function — see
    `_A2AServerRoute` and `_a2a_aauth_jsonrpc`; both share `_dispatch_jsonrpc`."""
    _authorize_inbound(current_user, agent_name)

    # Cap before parsing — an uncapped await request.json() lets one caller pin
    # memory. nginx caps at 25m, but :8000 may be reachable directly.
    raw = await request.body()
    return await _dispatch_jsonrpc(agent_name, request, raw, current_user=current_user)


# ---------------------------------------------------------------------------
# ent#623 — AAuth agent identity on the task endpoint (prototype, flag OFF)
# ---------------------------------------------------------------------------

#: What a bearer-less 401 advertises while AAuth is live.
_AAUTH_CHALLENGE_HEADERS = {
    "Accept-Signature": "sig=(" + " ".join(
        f'"{c}"' for c in aauth_httpsig.components_for("POST")
    ) + ")",
    "Accept-Signature-Scheme": "jwt",
    "AAuth-Requirement": "requirement=agent-token",
}

A2A_AAUTH_RATE_LIMIT = 60     # signed task requests per IP
A2A_AAUTH_RATE_WINDOW = 60


def _aauth_problem(exc: "aauth_verifier.AAuthError") -> JSONResponse:
    """RFC 9457 problem details; `Signature-Error` is the interoperable carrier."""
    headers = {}
    if exc.status == 401:
        headers["Signature-Error"] = f"error={exc.code}"
        if exc.code in ("invalid_input", "unsupported_scheme"):
            headers["Accept-Signature"] = _AAUTH_CHALLENGE_HEADERS["Accept-Signature"]
            headers["Accept-Signature-Scheme"] = "jwt"
    return JSONResponse(
        status_code=exc.status,
        media_type="application/problem+json",
        headers=headers,
        content={
            "type": f"urn:ietf:params:sig-error:{exc.code}",
            "error": exc.code,
            "detail": exc.detail,
        },
    )


def _aauth_request_facts(request: Request) -> "aauth_verifier.InboundRequest":
    raw_path = request.scope.get("raw_path") or request.url.path.encode("utf-8")
    if isinstance(raw_path, bytes):
        raw_path = raw_path.decode("latin-1")
    headers: Dict[str, str] = {}
    for name, value in request.headers.items():   # repeated fields joined, RFC 9110 §5.3
        headers[name] = f"{headers[name]}, {value}" if name in headers else value
    declared = request.headers.get("content-length")
    return aauth_verifier.InboundRequest(
        method=request.method,
        raw_path=raw_path.split("?", 1)[0],
        headers=headers,
        content_length=int(declared) if declared and declared.isdigit() else None,
    )


async def _a2a_aauth_jsonrpc(request: Request, issuer: str):
    """`POST /a2a/{name}` for a caller authenticated by AAuth agent identity.

    Refused before the body is parsed as JSON-RPC, like a bearer failure. The
    caller never becomes a Trinity `User`: access is exposure + an EXPLICIT
    allow-list entry for its verified identity (fail-closed), and no owner role
    travels with it.
    """
    agent_name = request.path_params["agent_name"]
    caller_ip = request.client.host if request.client else None

    # Limit first: everything below costs at least a DB read, and the caller is
    # still an unauthenticated stranger here.
    try:
        rate_limiter.enforce(
            f"a2a_aauth_ip:{_get_client_ip(request)}",
            A2A_AAUTH_RATE_LIMIT,
            A2A_AAUTH_RATE_WINDOW,
            detail="Too many signed A2A requests from this address.",
        )
    except HTTPException as exc:
        return JSONResponse(status_code=exc.status_code, content={"detail": exc.detail},
                            headers=exc.headers)
    if not db.get_a2a_exposed(agent_name):
        return JSONResponse(status_code=404, content={"detail": "Not found"})

    identities = a2a_gate.explicit_inbound_identities(agent_name)

    async def _read_body() -> bytes:
        chunks, total = [], 0
        async for chunk in request.stream():
            total += len(chunk)
            if total > _MAX_RPC_BODY_BYTES:
                raise aauth_verifier.AAuthError("invalid_input", "request body too large",
                                                status=413, trusted=True)
            chunks.append(chunk)
        return b"".join(chunks)

    try:
        verified, raw = await aauth_verifier.verify_request(
            _aauth_request_facts(request),
            expected_authority=aauth_config.issuer_host(issuer),
            trusted_identities=identities or [],
            read_body=_read_body,
            max_body_bytes=_MAX_RPC_BODY_BYTES,
        )
    except aauth_verifier.AAuthError as exc:
        # Only refusals past the trusted-issuer pre-gate are audited: before it,
        # the caller is an unauthenticated stranger and an audit row per request
        # would hand them the audit table.
        logger.info("[aauth] refused signed A2A request for %s: %s (%s)",
                    agent_name, exc.code, exc.identity or "unidentified")
        if exc.trusted:
            await platform_audit_service.log(
                event_type=AuditEventType.AUTHENTICATION, event_action="a2a_aauth_refused",
                source="a2a", actor_external_id=exc.identity, actor_ip=caller_ip,
                target_type="agent", target_id=agent_name, endpoint=str(request.url.path),
                details=aauth_inbound.audit_details(
                    None, identity=exc.identity, issuer=exc.issuer,
                    verification="failed", allowlist="not_evaluated", error=exc.code,
                ),
            )
        return _aauth_problem(exc)

    if not aauth_inbound.is_listed(verified.identity, identities):
        await platform_audit_service.log(
            event_type=AuditEventType.AUTHORIZATION, event_action="a2a_aauth_denied",
            source="a2a", actor_external_id=verified.identity, actor_ip=caller_ip,
            target_type="agent", target_id=agent_name, endpoint=str(request.url.path),
            details=aauth_inbound.audit_details(verified, allowlist="denied"),
        )
        await aauth_inbound.record_activity(agent_name, verified, allowlist="denied",
                                            error="caller not on the agent's A2A inbound allow-list")
        return JSONResponse(status_code=403,
                            content={"detail": "Caller not on the agent's A2A inbound allow-list"})

    return await _dispatch_jsonrpc(agent_name, request, raw, current_user=None, aauth=verified)


def _audit_actor(current_user: Optional[User], aauth) -> Dict[str, Any]:
    if aauth is not None:
        return {"actor_external_id": aauth.identity}
    return {"actor_user": current_user}


async def _dispatch_jsonrpc(
    agent_name: str,
    request: Request,
    raw: bytes,
    *,
    current_user: Optional[User],
    aauth: Optional["aauth_verifier.VerifiedAgent"] = None,
):
    """The JSON-RPC method table, shared by the bearer and AAuth entry points.

    Exactly one of `current_user` (bearer) / `aauth` (verified agent identity)
    is set. With `aauth` unset every line below behaves as it did before
    ent#623.
    """
    if len(raw) > _MAX_RPC_BODY_BYTES:
        return _rpc_error(None, _RPC_INVALID_REQUEST, "Request body too large")
    try:
        body = json.loads(raw)
    except Exception:
        return _rpc_error(None, _RPC_PARSE_ERROR, "Parse error: body is not valid JSON")

    if not isinstance(body, dict) or body.get("jsonrpc") != "2.0" or not isinstance(body.get("method"), str):
        return _rpc_error(body.get("id") if isinstance(body, dict) else None,
                          _RPC_INVALID_REQUEST, "Invalid JSON-RPC 2.0 request")

    method = body["method"]
    params = body.get("params") or {}
    rpc_id = body.get("id")
    if not isinstance(params, dict):
        return _rpc_error(rpc_id, _RPC_INVALID_PARAMS, "params must be an object")

    caller_ip = request.client.host if request.client else None

    # ---- message/send + message/stream ------------------------------------
    if method in ("message/send", "message/stream"):
        message = params.get("message")
        if not isinstance(message, dict):
            return _rpc_error(rpc_id, _RPC_INVALID_PARAMS, "params.message is required")
        text = _text_from_message(message)
        if not text:
            return _rpc_error(rpc_id, _RPC_INVALID_PARAMS, "message has no text parts")

        # Trigger-boundary dedup (Invariant #18): a re-delivered A2A message
        # with the same messageId must not double-execute. messageId absent →
        # dedup disabled (fail-open).
        message_id = message.get("messageId")
        decision = idempotency_service.begin(_a2a_idem_scope(agent_name, current_user, aauth), message_id)
        if decision.replay and not decision.in_flight and decision.snapshot:
            # A streaming client can't parse a bare JSON body — replay in the
            # transport it asked for.
            if method == "message/stream":
                return _replay_stream(rpc_id, decision.snapshot)
            return _rpc_result(rpc_id, decision.snapshot)
        if decision.in_flight:
            return _rpc_error(rpc_id, _RPC_INTERNAL_ERROR,
                              "A task for this messageId is already in progress", data={"retryable": True})

        if method == "message/stream":
            if aauth is not None:
                # ent#623: AAuth callers get message/send only (stated prototype scope).
                idempotency_service.fail(decision)
                return _rpc_error(rpc_id, _A2A_UNSUPPORTED,
                                  "message/stream is not supported for AAuth callers; use message/send")
            return await _stream_task(agent_name, text, current_user, rpc_id, decision, caller_ip)

        try:
            result = await _run_a2a_task(agent_name, text, current_user)
        except Exception as exc:  # noqa: BLE001 — never 5xx; A2A wants a JSON-RPC error
            idempotency_service.fail(decision)
            logger.warning("a2a message/send failed for %s: %s", agent_name, exc)
            return _rpc_error(rpc_id, _RPC_INTERNAL_ERROR, "Task execution failed")

        state = _a2a_state_for(result.status)
        task = _task_object(
            result.execution_id, state,
            text=result.response if state == "completed" else None,
            error=result.error if state == "failed" else None,
        )
        idempotency_service.complete(decision, result.execution_id, task)
        details = {"execution_id": result.execution_id, "state": state}
        if aauth is not None:
            aauth_inbound.remember_execution(result.execution_id, aauth.identity)
            details.update(aauth_inbound.audit_details(aauth, allowlist="allowed"))
            await aauth_inbound.record_activity(
                agent_name, aauth, allowlist="allowed",
                execution_id=result.execution_id, state=state,
                error=None if state == "completed" else f"task {state}",
            )
        await platform_audit_service.log(
            event_type=AuditEventType.EXECUTION, event_action="a2a_task", source="a2a",
            **_audit_actor(current_user, aauth), actor_ip=caller_ip,
            target_type="agent", target_id=agent_name,
            endpoint=str(request.url.path),
            details=details,
        )
        return _rpc_result(rpc_id, task)

    # ---- tasks/get --------------------------------------------------------
    if method == "tasks/get":
        exec_id = params.get("id")
        if not isinstance(exec_id, str) or not exec_id:
            return _rpc_error(rpc_id, _RPC_INVALID_PARAMS, "params.id is required")
        if aauth is not None and not aauth_inbound.execution_owned_by(exec_id, aauth.identity):
            return _rpc_error(rpc_id, _A2A_TASK_NOT_FOUND, "Task not found")
        row = db.get_execution(exec_id)
        # db.get_execution returns a ScheduleExecution object (not a dict) —
        # read via _exec_field so both the model and a dict work.
        if not row or _exec_field(row, "agent_name") != agent_name:
            return _rpc_error(rpc_id, _A2A_TASK_NOT_FOUND, "Task not found")
        status = _exec_field(row, "status")
        a2a_state = {
            "success": "completed", "failed": "failed", "cancelled": "canceled",
            "running": "working", "queued": "submitted",
        }.get(status, "working")
        return _rpc_result(rpc_id, _task_object(
            exec_id, a2a_state,
            text=_exec_field(row, "response") if a2a_state == "completed" else None,
            error=_exec_field(row, "error") if a2a_state == "failed" else None,
        ))

    # ---- tasks/cancel -----------------------------------------------------
    if method == "tasks/cancel":
        exec_id = params.get("id")
        if not isinstance(exec_id, str) or not exec_id:
            return _rpc_error(rpc_id, _RPC_INVALID_PARAMS, "params.id is required")
        if aauth is not None and not aauth_inbound.execution_owned_by(exec_id, aauth.identity):
            return _rpc_error(rpc_id, _A2A_TASK_NOT_FOUND, "Task not found")
        row = db.get_execution(exec_id)
        if not row or _exec_field(row, "agent_name") != agent_name:
            return _rpc_error(rpc_id, _A2A_TASK_NOT_FOUND, "Task not found")

        # Report what actually happened. Telling a caller "canceled" while the
        # task is still queued means it drains minutes later, runs, bills, and
        # performs side effects the caller believed were cancelled.
        status = _exec_field(row, "status")
        if status in ("success", "failed", "cancelled"):
            return _rpc_error(rpc_id, _A2A_TASK_NOT_CANCELABLE,
                              "Task is already in a terminal state")

        if status == "queued":
            # A queued row has no container process to signal — cancel it in the
            # backlog directly (the chat.py queued-cancel branch's shape). The
            # CAS inside cancel_queued_execution is what makes a lost race honest.
            cancelled = bool(db.cancel_queued_execution(
                exec_id, reason="Cancelled by A2A caller"))
        else:
            cancelled = bool(await terminate_execution_on_agent(agent_name, exec_id))

        if not cancelled:
            return _rpc_error(rpc_id, _A2A_TASK_NOT_CANCELABLE,
                              "Task could not be canceled")

        cancel_details = {"execution_id": exec_id}
        if aauth is not None:
            cancel_details.update(aauth_inbound.audit_details(aauth, allowlist="allowed"))
        await platform_audit_service.log(
            event_type=AuditEventType.EXECUTION, event_action="a2a_cancel", source="a2a",
            **_audit_actor(current_user, aauth), actor_ip=caller_ip,
            target_type="agent", target_id=agent_name,
            endpoint=str(request.url.path), details=cancel_details,
        )
        return _rpc_result(rpc_id, _task_object(exec_id, "canceled"))

    # ---- tasks/resubscribe (phased) --------------------------------------
    if method == "tasks/resubscribe":
        return _rpc_error(rpc_id, _A2A_UNSUPPORTED,
                          "tasks/resubscribe is not yet supported on this server")

    return _rpc_error(rpc_id, _RPC_METHOD_NOT_FOUND, f"Method not found: {method}")


def _replay_stream(rpc_id: Any, task: Dict[str, Any]) -> StreamingResponse:
    """Replay a stored task result to a `message/stream` caller in SSE.

    A streaming SDK has an event-stream parser attached; handing it a bare JSON
    body on replay breaks it. Same payload, right transport.
    """
    async def _gen():
        final = {"jsonrpc": "2.0", "id": rpc_id, "result": {**task, "final": True}}
        yield f"data: {json.dumps(final)}\n\n"

    return StreamingResponse(_gen(), media_type="text/event-stream")


async def _stream_task(agent_name: str, text: str, current_user: User,
                       rpc_id: Any, decision, caller_ip: Optional[str]) -> StreamingResponse:
    """message/stream via SSE. Emits a `working` status event, runs the task,
    then a terminal task event. Non-incremental (the agent turn is atomic), but
    spec-shaped so a streaming A2A client attaches and receives the result."""
    async def _gen():
        # Initial status: the server has accepted the task and is working.
        working = {"jsonrpc": "2.0", "id": rpc_id, "result": {
            "kind": "status-update",
            "status": {"state": "working"},
            "final": False,
        }}
        yield f"data: {json.dumps(working)}\n\n"
        try:
            result = await _run_a2a_task(agent_name, text, current_user)
        except asyncio.CancelledError:
            # A client disconnect cancels the generator, and CancelledError is a
            # BaseException (3.8+) — the `except Exception` below never sees it.
            # Without this, neither complete() nor fail() runs, the row stays
            # in_flight, and every retry with this messageId gets "already in
            # progress" for the full 24h TTL.
            idempotency_service.fail(decision)
            raise
        except Exception as exc:  # noqa: BLE001
            idempotency_service.fail(decision)
            logger.warning("a2a message/stream failed for %s: %s", agent_name, exc)
            err = {"jsonrpc": "2.0", "id": rpc_id, "error": {
                "code": _RPC_INTERNAL_ERROR, "message": "Task execution failed"}}
            yield f"data: {json.dumps(err)}\n\n"
            return
        state = _a2a_state_for(result.status)
        task = _task_object(
            result.execution_id, state,
            text=result.response if state == "completed" else None,
            error=result.error if state == "failed" else None,
        )
        idempotency_service.complete(decision, result.execution_id, task)
        await platform_audit_service.log(
            event_type=AuditEventType.EXECUTION, event_action="a2a_task_stream", source="a2a",
            actor_user=current_user, actor_ip=caller_ip,
            target_type="agent", target_id=agent_name, details={"execution_id": result.execution_id},
        )
        final = {"jsonrpc": "2.0", "id": rpc_id, "result": {**task, "final": True}}
        yield f"data: {json.dumps(final)}\n\n"

    return StreamingResponse(_gen(), media_type="text/event-stream")


# ===========================================================================
# #736 — outbound A2A calls (a Trinity agent tasks an EXTERNAL A2A agent)
# ===========================================================================
#
# Route ordering (Invariant #4) is not at risk here, and it is worth saying why
# rather than asserting it: the `/api/agents` catch-all is
# `@router.get("/{agent_name}")` — a GET, and a path parameter matches exactly
# one segment. These are POSTs with three segments, and the identical shape
# (`GET /{agent_name}/a2a/agent-card`, #737) has coexisted with that catch-all
# since Phase 1. A regression test asserts they resolve anyway, because this is
# the kind of thing a later refactor breaks silently.

#: Refusals that are the CALLER's fault (a bad reference, a registry row that
#: cannot legally be fetched) → 4xx. Everything else that went wrong out on the
#: wire is the peer's → 502/504.
_A2A_CLIENT_ERROR_STATUS = {
    "endpoint_not_https": 400,
    "endpoint_private_address": 400,
    "endpoint_dns_failure": 400,
    "endpoint_invalid": 400,
    "message_too_long": 422,
    "timeout": 504,
}


def _map_call_error(exc: A2ACallError) -> HTTPException:
    """`A2ACallError.reason` → HTTP. One mapping, used by both routes.

    Defaults to **502**, which is the honest answer for "the peer did something
    we refused or could not use" — including the case that matters most, a
    JSON-RPC error arriving on HTTP 200. Returning 200 with the peer's error
    text as if it were an answer is the silent-success path this whole feature
    has to avoid.
    """
    status_code = _A2A_CLIENT_ERROR_STATUS.get(exc.reason, 502)
    detail = {"reason": exc.reason, "message": exc.detail}
    if exc.remote_code is not None:
        detail["remote_code"] = exc.remote_code
    return HTTPException(status_code=status_code, detail=detail)


def _assert_outbound_self(current_user: User, agent_name: str) -> None:
    """An agent-scoped key may place outbound calls only AS ITSELF.

    `AuthorizedAgentByName` resolves an agent key to its OWNER and checks owner
    access, so without this a permitted sibling could place calls under a
    neighbour's name.

    Be precise about what that buys, because the obvious reading is wrong under
    the shipped OSS provider: endpoints there are **platform-scope**, so there
    is no "own" versus "neighbour" credential — every agent may name every
    registered endpoint. What this check protects is **attribution**: the
    rate-limit key, the audit row and the `agent_activities` row all name the
    agent that actually spent the call, so a sibling cannot launder its egress
    through a neighbour. It also holds the line for a future per-agent provider,
    where the obvious reading becomes the literal one — which is why it is here
    now rather than added later, after the surface has callers.

    `reject_agent_principal` is deliberately NOT used. This is a *use* of a
    capability an admin already granted by registering the endpoint, not a
    *grant* of one (the Invariant #8 line) — refusing agent principals here
    would make the feature unreachable by the only callers it exists for.
    """
    if current_user.agent_name and current_user.agent_name != agent_name:
        raise HTTPException(
            status_code=403,
            detail="An agent may only place outbound A2A calls as itself",
        )


def _require_outbound_enabled() -> None:
    """404 when the kill switch is off (§32.5 FR-11).

    404, not 403: "this capability is not present" is answered with a 404
    everywhere else in Trinity, and it keeps a disabled deployment from
    advertising a surface it will not serve.
    """
    if not a2a_outbound_service.is_outbound_enabled():
        raise HTTPException(status_code=404, detail="Not found")


@router.post("/{agent_name}/a2a/call", response_model=A2ACallResponse)
async def call_a2a_agent(
    agent_name: AuthorizedAgentByName,
    body: A2ACallRequest,
    request: Request,
    current_user: User = Depends(get_current_user),
):
    """Task an external A2A agent from `agent_name` and return its answer (#736).

    Behaviour worth knowing before you change it (§32.5 FR-18 notes):

    * **The agent container need not be running.** The call is made by the
      backend, not by the agent, so a stopped agent's owner can still drive its
      registered endpoints. That is a property of where the fetcher lives, not
      an oversight.
    * **Read-only mode and `autonomy_enabled` do not gate this.** Read-only
      governs source writes inside the container; autonomy governs whether the
      *scheduler* fires proactive work. This is a caller-initiated action.
    * **An ephemeral ghost's own key is refused**, by construction rather than
      by a check here: this route is not on the trinity-enterprise#69 fence's
      allowlist, so `_enforce_ephemeral_key_fence` 403s it at the auth entry
      point. Recorded so nobody "adds it for convenience" later — a disposable
      agent running untrusted work is the last principal that should be able to
      spend a stored credential.
    """
    _require_outbound_enabled()
    _assert_outbound_self(current_user, agent_name)

    try:
        outcome = await a2a_outbound_service.call_agent(
            agent_name=agent_name,
            endpoint_ref=body.endpoint,
            message=body.message,
            dedup_label=body.dedup_label,
            context_id=body.context_id,
            task_id=body.task_id,
            execution_id=body.execution_id,
            caller_agent_name=current_user.agent_name,
        )
    except A2AOutboundDisabled:
        raise HTTPException(status_code=404, detail="Not found")
    except A2AEndpointNotFound:
        raise HTTPException(
            status_code=404,
            detail={
                "reason": "endpoint_not_found",
                "message": (
                    "No outbound A2A endpoint is registered under that name. An "
                    "administrator registers endpoints; agents choose among them "
                    "by name."
                ),
            },
        )
    except EffectInProgressError as exc:
        raise HTTPException(status_code=409, detail=str(exc))
    except A2AAAuthRefused as exc:
        raise HTTPException(status_code=exc.status_code,
                            detail={"reason": exc.reason, "message": exc.detail})
    except A2ACallError as exc:
        raise _map_call_error(exc)

    await platform_audit_service.log(
        event_type=AuditEventType.EXECUTION,
        event_action="a2a_outbound_call",
        source="api",
        actor_user=current_user,
        actor_ip=request.client.host if request.client else None,
        target_type="agent",
        target_id=agent_name,
        endpoint=str(request.url.path),
        request_id=getattr(request.state, "request_id", None),
        details=a2a_outbound_service.audit_details(outcome),
    )

    result = outcome.result
    return A2ACallResponse(
        state=result.state,
        text=result.text,
        task_id=result.task_id,
        context_id=result.context_id,
        truncated=result.truncated,
        protocol_version=result.protocol_version,
        endpoint=outcome.endpoint_name,
        replayed=outcome.replayed,
    )


@router.post("/{agent_name}/a2a/task", response_model=A2ACallResponse)
async def get_a2a_task(
    agent_name: AuthorizedAgentByName,
    body: A2ATaskRequest,
    request: Request,
    current_user: User = Depends(get_current_user),
):
    """Poll a remote A2A task by id on a registered endpoint (#736).

    This is what makes the 30s RPC timeout safe rather than lossy: a remote that
    answers `working` hands back a `task_id`, and without a poll route that id
    would be a handle to nothing. The two are one decision.

    Deliberately NOT `effect_guard`-wrapped — a poll is a read, and deduping it
    would answer "has it finished yet?" from a cached snapshot of the last time
    it had not.
    """
    _require_outbound_enabled()
    _assert_outbound_self(current_user, agent_name)

    try:
        outcome = await a2a_outbound_service.poll_task(
            agent_name=agent_name,
            endpoint_ref=body.endpoint,
            task_id=body.task_id,
            caller_agent_name=current_user.agent_name,
        )
    except A2AOutboundDisabled:
        raise HTTPException(status_code=404, detail="Not found")
    except A2AEndpointNotFound:
        raise HTTPException(
            status_code=404,
            detail={"reason": "endpoint_not_found",
                    "message": "No outbound A2A endpoint is registered under that name."},
        )
    except A2AAAuthRefused as exc:
        raise HTTPException(status_code=exc.status_code,
                            detail={"reason": exc.reason, "message": exc.detail})
    except A2ACallError as exc:
        raise _map_call_error(exc)

    result = outcome.result
    return A2ACallResponse(
        state=result.state,
        text=result.text,
        task_id=result.task_id,
        context_id=result.context_id,
        truncated=result.truncated,
        protocol_version=result.protocol_version,
        endpoint=outcome.endpoint_name,
    )
